#################### default parameters ################################
# favicon
favicon = "images/favicon.png"
# logo
logo = "images/em-logo-lightmode.png"
logo_darkmode = "images/em-logo-darkmode.png"
# use `px` or `x` with logo_width, example: "100px".
# Note: logo_width is not work with .svg file
logo_width = "500px"
logo_height = "75px"
# if logo_webp set false, will not generate WEBP version of logo | default is true
logo_webp = true
# logo text will only show when logo is missing.
logo_text = "Essential Millennial"
# navbar fixed to top
navbar_fixed = true
# theme-mode
theme_switcher = true
theme_default = "dark" # available options [light/dark/system]
# Main Sections
mainSections = ["blog"]
# contact form action
contact_form_action = "https://formspree.io/f/xaygqgzd" # contact form works with [https://airform.io/] or [https://formspree.io]
# google tag manager, see https://developers.google.com/tag-manager/
google_tag_manager = "" # example: G-XXXXXXXXXX
google_adsense = ""     # example: ca-pub-xxxxxxxxxxxxxxxx
# custom script on header, example: custom_script= "<script>console.log(\"Hello World\")</script>"
custom_script = ""
# copyright
copyright = "Website by [Metasense](https://metasense.one)"

# Preloader
[preloader]
enable = false
preloader = "" # use jpg, png, svg or gif format.

# Navigation button
[navigation_button]
enable = true
label = "get a quote"
link = "contact"

# search
[search]
enable = true
primary_color = "#121212"
include_sections = ["blog"]
show_image = true
show_description = true
show_tags = true
show_categories = true


# seo meta data for OpenGraph / Twitter Card
[metadata]
keywords = ["Digital Marketing Strategy", "Social Media Management", "Content Creation", "Video Marketing", "PPC Advertising", "SEO Services", "Email Marketing", "Graphic Design", "Web Development", "Branding and Marketing Strategies", "Content Strategy", "Customer Engagement"]
description = "Essential Millennial: Digital Marketing Agency    Your strategic partner in digital marketing. Elevate your brand with expert services in SEO, social media management, video marketing, and more. Unlock growth with our tailored solutions."
author = "essentialmillenial.com"
image = "/images/meta.jpeg"


# site verifications
[site_verification]
google = ""   # Your verification code
bing = ""     # Your verification code
baidu = ""    # Your verification code
facebook = "3n6g01iqnzc0fc63cb2u8vu05acy4f" # Your verification code
mastodon = "" # Your verification code

# cookies
[cookies]
enable = false
expire_days = 60
content = "This site uses cookies. By continuing to use this website, you agree to their use."
button = "I Accept"

######################## sidebar widgets #########################
[widgets]
sidebar = ["categories", "tags"]


# google map
[google_map]
enable = false
map_api_key = "AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"


# Subscription
[subscription]
enable = true
# mailchimp subsciption
mailchimp_form_action = "https://essentialmillennial.us4.list-manage.com/subscribe/post?u=3120e0236bbe0b71fe4fefad3&amp;id=1da0a3ec8f&amp;f_id=00b851e8f0&SIGNUP={{ .Permalink }}" # replace this url with yours
mailchimp_form_name = "b_3120e0236bbe0b71fe4fefad3_1da0a3ec8f"
